correction push games cards when category is clicked
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G3-readyplayerfound pull request #19
Opened 2024-04-21 15:09 UTC by audreybaudry

2024-04-23 12:45 UTC, PMorganGit approved these changes

2024-04-23 15:40 UTC, fantinerudent requested changes

2024-04-23 15:40 UTC, fantinerudent commented on client/src/components/Categories/Api.jsx
> +const getGame = (id) => axiosCreate.get(`/games?genres=${id}&key=${key}`);
get gameSSSSS by genre ?

2024-04-23 15:40 UTC, fantinerudent commented on client/src/components/Categories/Api.jsx
> +const getGame = (id) => axiosCreate.get(`/games?genres=${id}&key=${key}`);
et au lieu de id mettre : idGenre

2024-04-23 15:40 UTC, fantinerudent commented on client/src/components/Categories/Categories.jsx
> +                  className="image_categorie"
category

( faute à corriger à plusieurs endroits )

2024-04-23 15:40 UTC, fantinerudent commented on client/src/components/CategoryPage/CategoryCard.jsx
> +            {game.map((jeu) => (
franglais

2024-04-24 07:46 UTC, fantinerudent requested changes

2024-04-24 07:46 UTC, fantinerudent commented on client/src/components/CategoryPage/CategoryCard.jsx
> +            {games.map((jeu) => (
toujours du franglais avec "jeu"

2024-04-24 07:46 UTC, fantinerudent commented on client/src/components/Categories/Categories.jsx
>                  className="image_categorie"
category

2024-04-24 07:46 UTC, fantinerudent commented on client/src/components/Categories/Categories.jsx
> +              className="categorie_card"
category

2024-04-24 07:46 UTC, fantinerudent commented on client/src/components/Categories/Categories.jsx
> +                <h4 className="categorie_name">{item.name}</h4>
category.
( fais gaffe parce que cette class category_name existe déjà je crois, ça risque de faire sauter ton css si juste tu la renommes )

2024-04-24 08:09 UTC, fantinerudent approved these changes

2024-04-24 08:17 UTC, merged