Filter display platforms
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G3-readyplayerfound pull request #31
Opened 2024-04-25 14:07 UTC by audreybaudry

Title for the category cards 
Platforms display on cards filtered

2024-04-25 14:27 UTC, saile117 approved these changes

2024-04-25 14:40 UTC, fantinerudent requested changes

2024-04-25 14:40 UTC, fantinerudent commented on client/src/components/Search/Results.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
@saile117 Sait régler ça maintenant :D

2024-04-26 08:04 UTC, audreybaudry commented on client/src/components/Search/Results.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
C'est bon normalement :)

2024-04-26 08:24 UTC, fantinerudent approved these changes

2024-04-26 08:51 UTC, merged