Detail cards
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G3-readyplayerfound pull request #33
Opened 2024-04-26 12:37 UTC by MontandonArnauld

Ajout de la fonction redirection sur l'ensemble des cards vers le site web du jeu video

2024-04-26 12:45 UTC, audreybaudry approved these changes

2024-04-26 13:12 UTC, fantinerudent requested changes

2024-04-26 13:12 UTC, fantinerudent commented on client/src/contexts/GameContext.jsx
> +
commentaiiiires

2024-04-29 07:35 UTC, fantinerudent approved these changes

2024-04-29 07:41 UTC, merged