link de la navbar vers home
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G3-readyplayerfound pull request #36
Opened 2024-04-26 13:19 UTC by saile117

2024-04-26 14:50 UTC, audreybaudry approved these changes

2024-04-29 07:37 UTC, fantinerudent requested changes

2024-04-29 07:37 UTC, fantinerudent commented on client/src/components/Navbar/Navbar.jsx
> +                <Link to="./">
pourquoi une balise a dans un Link ?

2024-04-29 07:37 UTC, fantinerudent commented on client/src/components/Navbar/Navbar.jsx
> +                      src="../../../public/button/home.png"
/public

2024-04-29 07:37 UTC, fantinerudent commented on client/src/components/Navbar/Navbar.jsx
> +                    src="../../../public/button/rechercher.png"
/public

2024-04-29 07:37 UTC, fantinerudent commented on client/src/components/Navbar/Navbar.jsx
> +                  <a
?

2024-04-29 07:41 UTC, saile117 commented on client/src/components/Navbar/Navbar.jsx
> +                <Link to="./">
car on a le link depuis les autres pages et le scroll

2024-04-29 07:52 UTC, saile117 commented on client/src/components/Navbar/Navbar.jsx
> +                  <a
je ne comprends pas la requête ?

2024-04-29 09:02 UTC, MontandonArnauld approved these changes

2024-04-29 09:28 UTC, fantinerudent approved these changes

2024-04-29 09:29 UTC, merged